# EpicCraftingsRequireItemHook Configuration
version: 1.1

# Item commands - use MMOItems ID (UPPERCASE)
items-command:
  BICHNHA:
    1: '[console] ecraft opencraft %player_name% phongan'
    2: '[console] ecraft opencraft %player_name% trai_tim_linh_bien'

  BANGTHANKIEM1:
    1: '[console] ecraft opencraft %player_name% bang_than_kiem2'
    2: '[console] ecraft opencraft %player_name% bang_tinh_loc'

  BANGTHANKIEM:
    1: '[console] ecraft opencraft %player_name% bang_tinh_loc'
    2: '[console] ecraft opencraft %player_name% bang_than_kiem1'

  # Fallback when recipe not found
  default_crafting:
    1: '[message] &cKhông tìm thấy công thức cho item này'
    2: '[message] &cKhông tìm thấy công thức cho item này'
    3: '[message] &cKhông tìm thấy công thức cho item này'
    4: '[message] &cKhông tìm thấy công thức cho item này'

# Slot mapping for require items
slot-mapping:
  positions:
    1: 10    # Position 1 = Slot 10
    2: 11    # Position 2 = Slot 11
    3: 12    # Position 3 = Slot 12
    4: 13    # Position 4 = Slot 13
    5: 19    # Position 5 = Slot 19
    6: 20    # Position 6 = Slot 20
    7: 21    # Position 7 = Slot 21
    8: 22    # Position 8 = Slot 22
    9: 28    # Position 9 = Slot 28
    10: 29   # Position 10 = Slot 29
    11: 30   # Position 11 = Slot 30
    12: 31   # Position 12 = Slot 31

# Plugin settings
settings:
  debug: true

# Command settings
commands:
  cooldown:
    enabled: true
    duration: 1